// vue/client/components/stateless.component.tsx
import * as Vue from 'vue';

interface IProps {
  opacity: number;
}

export let StatelessComponent = Vue.component('stateless-component', {
  
  functional: true,

  render: (h, context) => {
    let props: IProps = Object.prototype.valueOf.call(context.data);
    
    return h('div',
      {
        domProps: {
          className: 'base-class',
          style: 'opacity:'+ props.opacity
        }
      },
      [
        h('h2', 'Properties'),
        h('p','Opacity: ' + props.opacity)
      ]
    )
  }
});

// react/client/app/stateless.component.tsx
import * as React from 'react'
import {Block} from "./block.component";

//--------------------
// Stateless component
//--------------------


interface IProps {
  opacity: number;
}

export const StatelessComponent = (props: IProps) => {
  return (
    <Block opacity={props.opacity}>
      <h2>Properties:</h2>
      <p>Opacity: {props.opacity.toString()}</p>
    </Block>
  );
};
