// angular/imports/statefull.component.ts
import {Component, HostListener, ViewEncapsulation} from '@angular/core';
import {Block} from "../../react/client/app/block.component";

@Component({
  inputs: ['opacity'],
  selector: 'statefull-component',
  encapsulation: ViewEncapsulation.Native,
  template: `
    <html [ngStyle]="{
        'opacity': opacity,
        'cursor': 'pointer'
      }">

      <block-component (click)="onClick()">
          
        <h2>Properties</h2>
        <p>Opacity: {{opacity}}</p>
          
        <h2>State</h2>
        <p>Hovered: {{hovered}}</p>
        <p>Clicked: {{clicked}}</p>
          
      </block-component>
    </html>
  `
})

export class StatefullComponent {
  hovered = false;
  clicked = 0;
  opacity = 0.8;

  onClick() {
    this.clicked++;
  }

  @HostListener('mouseenter') onMouseEnter() {
    this.hovered = true;
  }
  @HostListener('mouseleave') onMouseLeave() {
    this.hovered = false;
  }
}

// vue/client/components/statefull.component.tsx
import * as Vue from 'vue';

export let StatefullComponent = Vue.component('statefull-component',{

  functional: false,
  
  props:['opacity'],

  data: () => {
    return {
      clicked: 0,
      hovered: false,
    }
  },
  
  render(h) {
    
    return h('div',
      {
        domProps: {
          className: 'base-class hoverable',
          style: 'opacity: ' + this.opacity
        },
        on: {
          click: () => {
            this.clicked++;
          },
          mouseenter: () => {
            this.hovered = true;
          },
          mouseleave: () => {
            this.hovered = false;
          }
        },
      },
      [
        h('h2', 'Properties'),
        h('p', 'Opacity: ' + this.opacity),
        h('h2', 'State'),
        h('p', 'Hovered: ' + this.hovered),
        h('p', 'Clicked: ' + this.clicked)
      ]
    )
  }
});
